### ISSUE TITLE
App não funciona bem no modo paisagem

### ISSUE THREAD

**Issue by RodrigoDavy** [rubensfelipe/ReceitaBoa#4]
Contexto
---------
Ao virar de lado o celular, partes do app ficam inutilizáveis ou com um layout ruim. Na parte de editar receita, ao tirar uma foto sem salvar e girar o celular, a foto desaparece

Proposta
----------
Colocar o app para funcionar apenas no modo vertical

Critério de aceitação
---------------------
O app não deve mudar para o layout horizontal em nenhuma das activities

Pull Request
-------------
https://github.com/rubensfelipe/ReceitaBoa/pull/5 (deve ser revisado e aprovado)

QA (Passos para validação/teste)
----------------------------------
Teste 1:

- Abrir o app
- Em cada activities, tentar girar o celular para a posição horizontal
- Não deveria mudar para o layout horizontal em nenhuma delas

Teste 2:
- Editar uma receita
- Tirar uma foto com a câmera e apertar o botão de aceitar
- Virar o celular para a horizontal
- Não deveria mudar para o layout horizontal e a foto se deve manter antes de salva

**Comment by RodrigoDavy** [comment]
Vou deixar um TODO para você validar o ticket:

- Ir ao Pull Request
- Revisar o código e aprovar
- Se tiver alguma alteração no computador que não tiver subido ao Github, fazer push ou stash (referência do git-stash: https://git-scm.com/docs/git-stash)
- Mudar a rama para a do hotfix (hotfix/0.0.0.1)
- Fazer os testes que descrevi em QA
- Caso funcione tudo bem, comente neste issue "Validado"
- Me avise quando terminar ou qualquer dúvida

**Comment by RodrigoAIM** [comment]
Documentação sobre o que são ramas do Github: https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

**Comment by rubensfelipe** [comment]
Validado
